name: DATASOURCE

on:
  push:
    branches:
      - "v*.*.*"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                  - 
                    dockerfile: ./Dockerfile.datasource.server
                    image: wiliehidayat87/mediaplatform-datasource-server
                        
        permissions:
            contents: read
            packages: write

        steps:
        -
            name: Checkout
            uses: actions/checkout@v4

        -
            name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ matrix.image }}
                tags: |
                    type=schedule
                    type=ref,event=branch
                    type=ref,event=pr
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}
                    type=semver,pattern={{major}}
                    type=sha
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
            
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
                platforms: linux/amd64
                context: .
                file: ${{ matrix.dockerfile }}
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}